// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[] = SECRET_SSID;           // Network SSID (name)
const char PASS[] = SECRET_OPTIONAL_PASS;  // Network password (use for WPA, or use as key for WEP)

CloudTemperatureSensor cloud_sht45Temperature;
CloudRelativeHumidity cloud_sht45Humidity;
CloudTemperatureSensor cloud_scd41Temperature;
CloudRelativeHumidity cloud_scd41Humidity;
CloudCounter cloud_scd41CO2Concentration;
CloudCounter cloud_sgp40VocRaw;
CloudCounter cloud_sgp40VocIndex;
CloudTemperatureSensor cloud_bmp180Temperature;
CloudPressure cloud_bmp180Pressure;

void initProperties() {
  ArduinoCloud.addProperty(cloud_sht45Temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloud_sht45Humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloud_scd41Temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloud_scd41Humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloud_scd41CO2Concentration, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloud_sgp40VocRaw, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloud_sgp40VocIndex, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloud_bmp180Temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloud_bmp180Pressure, READ, ON_CHANGE, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
